### ISSUE TITLE
quickstart bugs

### ISSUE THREAD

**Issue by mkuratczyk** [slawlor/ractor#141]
Small issues on https://slawlor.github.io/ractor/quickstart/ (I couldn't find a repo for these docs, so posting here):

1. `type MyFirstActor;` should be `struct MyFirstActor;` (or `pub struct`, perhaps combined with `pub enum`)
2. `[tokio::main]` should be `#[tokio::main]`

There are also warnings about unused variables, but I guess that's fine in a hello world example.

Thanks for a very interesting project!

**Comment by slawlor** [comment]
Thanks @mkuratczyk for reporting! They've been fixed and the site is updating.
