### ISSUE TITLE
Add `Scope`-> `GroupName` mapping

### ISSUE THREAD

**Issue by leonqadirie** [slawlor/ractor#184]
Relating to https://github.com/slawlor/ractor/pull/177#discussion_r1363016547:

> This is where having another index might be helpful, i.e. Scope -> Group name in a separate mapping. But that's an optimization that can be added in the future.

To make sure I understand you correctly before tackling this:
Are we talking about sth. along the lines of substituting `ScopeGroupKey` with sth. like this?

```rust
pub struct Scope {
    name: ScopeName,
    groups: HashSet<GroupName>,
}
```

**Comment by slawlor** [comment]
Sorry again on the delay getting back to you. I meant another global index linking the scopes to groups. So you could efficiently lookup the groups from a given scope. This would remove some scan operations but it is a minimal operation.

**Comment by leonqadirie** [comment]
No problem, again, take all the time required. Hope all is fine and you get some sleep ;)
Will open a PR with what I understood this to be.

**Comment by slawlor** [comment]
#190 resolved this.
