### ISSUE TITLE
Log messages

### ISSUE THREAD

**Issue by slawlor** [slawlor/ractor#22]
We have 0 log messages in the actor flow, and definitely need some. Let's standardize on the `log` crate.

**Comment by slawlor** [comment]
Yes I just haven't worked with it yet, but am very open to standardizing on tracing. I've heard good things, just haven't worked with it yet.

**Comment by theduke** [comment]
Strong +1 for tracing.

It's pretty much the standard now in the async and server related Rust ecosystem.

On a basic level usage is pretty much equivalent to `log`:

```
tracing::trace!(field=%variable, "hello");
```

Note that `async` provides quite a few challenges for tracking logging scopes.

You'll want to use [tracing_futures](https://docs.rs/tracing-futures/latest/tracing_futures)  and [instrument](https://docs.rs/tracing/latest/tracing/instrument/index.html)

**Comment by jsgf** [comment]
I'd prefer tracing. The log crate does in principle have a shim to tracing, but it isn't very complete (eg logs with structured values don't work).

I think we also need to put more tracing-qua-tracing into ractor, so it would be suboptimal to have both.

**Comment by quietlychris** [comment]
I'd also like to add a +1 for `tracing` as well--I think there's probably a fairly natural flow for people starting with the `tokio` runtime before eventually looking for an actor framework like `ractor`.

**Comment by slawlor** [comment]
Closing as completed!
