### ISSUE TITLE
Add a pre_stop fn or some way to wait until post_stop has finished

### ISSUE THREAD

**Issue by lucasmerlin** [slawlor/ractor#254]
**Is your feature request related to a problem? Please describe.**
I have some actors where I perform finalization operations when the actor is stopped, and need to wait until those have finished. 
I assumed that post_stop would be executed before stop_and_wait finishes but it seems like that isn't the case. Would it be possible to add a pre_stop function to the Actor trait or alternatively wait until post_stop is finished in stop_and_wait?

**Describe the solution you'd like**
Add a `pre_stop` function to the Actor trait.

**Describe alternatives you've considered**
Right now I'm sending a custom stop message with a reply port to my actor to stop it but that is inconvenient and I now need to remember which actors must be stopped with their custom stop message.

**Comment by slawlor** [comment]
This seems reasonable to add but for now as a workaround can you wait on the initial creation join handle? That only exists once the actor is 100% dead. 

You can also check the actors state enum which is an atomic under the hood to verify it's state

**Comment by slawlor** [comment]
@lucasmerlin this was indeed a bug. I have a fix and i'll push an updated crate to 0.10.4 today. Thanks for the find!

**Comment by lucasmerlin** [comment]
Awesome, this will make my shutdown code much nicer!
