### ISSUE TITLE
Dont gate factory behind `async-trait`

### ISSUE THREAD

**Issue by seanaye** [slawlor/ractor#272]
**Is your feature request related to a problem? Please describe.**

Currently its not possible to use the factory if async_trait feature is disabled

**Describe the solution you'd like**

it would be nice if we could use factories when not using async trait

**Describe alternatives you've considered**

N/A

**Additional context**
I saw this issue but it was closed, this is still a problem in the latest release

https://github.com/slawlor/ractor/issues/248

**Comment by slawlor** [comment]
This isn't something that's possible today because of missing functionality with native async traits. This is the content I made when someone else opened an issue on this

https://github.com/slawlor/ractor/issues/248#issuecomment-2198793211

**Comment by slawlor** [comment]
The landing page of the `async-trait` crate outlines the problem as well: https://crates.io/crates/async-trait

We might be able to move to a mixed model, where some traits are using `Box`ed futures, but I'm concerned about the impacted ergonomics.
