### ISSUE TITLE
Log format is changed.

### ISSUE THREAD

**Issue by FancyQian** [slawlor/ractor#297]
**Describe the bug**
I upgraded from "0.10.2" to "0.13.3" and I found that the prefix of the log is not the name of a single atcor, but also includes the chain of supervisors. Although this is good to tracing, a very simple log will become very long. Which code is related to this modification? Or how to configure it to shorten it to a concise log?

```
2024-12-06T09:50:56.369278Z  INFO Actor{id="0.7" name="ConnectionService"}:Actor{id="0.17" name="192.168.1.18:33456"}:Actor{id="0.19" name="192.168.1.18:33456-reader"}: Onboarding: ....
```

**To Reproduce**
Supervisors actor, tracing log, log init code
```
          let dir = tracing_subscriber::filter::Directive::from(LevelFilter::from(log_level));
      
          let filter = vec![dir]
              .into_iter()
              .fold(EnvFilter::from_default_env(), |filter, directive| {
                  filter.add_directive(directive)
              });

            use tracing_glog::Glog;
            use tracing_glog::GlogFields;

            let fmt = tracing_subscriber::fmt::Layer::default()
                .with_ansi(stderr().is_terminal())
                .with_writer(std::io::stderr)
                .event_format(Glog::default().with_timer(tracing_glog::LocalTime::default()))
                .fmt_fields(GlogFields::default().compact());

            let subscriber = Registry::default().with(filter).with(fmt);
            tracing::subscriber::set_global_default(subscriber)
                .expect("to set GLOG global subscriber");
```

**Expected behavior**
The log can be shorten or flexible customization

**Comment by slawlor** [comment]
This was changed in #266

You can probably customize your tracing subscriber to exclude/truncate it, but at the moment tracing propagation is automatically added for you. We did look at making it optional, however the ergonomics were deemed too clunky and we decided better to opt-in universally.

However for the supervisor->child logging, it should only double-print the actor id during pre_start() messages, since that executes on the supervisor's blocking `spawn` or `spawn_linked`. Once the child is started and running, future messages will only show the child id.

**Comment by FancyQian** [comment]
@slawlor thanks, the ture thing is the  supervisor->child logging is not only "double-print the actor id during pre_start()" messages in my project, let me deep into that..

**Comment by FancyQian** [comment]
Looks like each actor handler has span message as well, it may too noise..
```
        // The current [tracing::Span] is retrieved, boxed, and included in every
        // `BoxedMessage` during the conversion of this `TActor::Msg`. It is used
        // to automatically continue tracing span nesting when sending messages to Actors.
        let current_span_when_message_was_sent = msg.span.take();

        // An error here will bubble up to terminate the actor
        let typed_msg = TActor::Msg::from_boxed(msg)?;

        if let Some(span) = current_span_when_message_was_sent {
            handler
                .handle(myself, typed_msg, state)
```

**Comment by slawlor** [comment]
I'm adding an opt-out feature for this. it'll be enabled by default, but can selectively be turned off

**Comment by texascloud** [comment]
Does an opt-out fix the problem of the spans looking goofy?

**Comment by FancyQian** [comment]
@texascloud yes, the #299 is working as expected
```
ractor = { version = "0.13.5", default-features = false, features = ["tokio_runtime", "async-trait"] }
```
