### ISSUE TITLE
Waiting for actors to finish by ActorRef/ActorCell

### ISSUE THREAD

**Issue by fhilgers** [slawlor/ractor#303]
**Is your feature request related to a problem? Please describe.**

When an actor is spawned, one gets access to its `JoinHandle` which allows us to wait for the actor to finish. However, if I am getting an actor from the Registry or if I do not want to pass around the JoinHandle everywhere, there is no good option to just wait for the actor to finish.

Using methods like `stop_and_wait`, `drain_and_wait`, `kill_and_wait` already allow us to wait for the actor to complete, but they require us to do an action which eventually stops the actor.

This issue came up, because draining a factory requires sending the `FactoryMessage::DrainRequests` which has no way to wait for all messages to be processed.

**Describe the solution you'd like**

Something like `actor_cell.wait().await` or even `actor_cell.await`.

**Describe alternatives you've considered**

Creating a dummy actor and link the actor I want to wait for to that dummy actor either as supervisor or as child. However that requires me to spawn another task and I am not quite sure what happens when the actor finished in the time between linking and spawning (I have always double checked the status).

Looping in an interval and check the actor status.

**Additional context**

The implementation should be trivial, if I understood the code correctly, one could just have:

```rust
impl ActorProperties {
  async fn wait() {
    self.wait_handler.notified().await
  }
}
```

which should be triggered when the actor status is set to stopped.

**Comment by slawlor** [comment]
Please feel free to put up a pr. This should be relatively trivial as you stated and is a great addition!

**Comment by stemcc** [comment]
This would definitely be a great addition. 

I'm refactoring a large Actix project where all the actors have implemented an Actix `stopping` trait that provides an opportunity to run code before the `stop` trait, which is the final opportunity to run code in the actor's lifecycle (so akin to Ractor's `post_stop` handler method). 


It seems potentially like this enhancement could be where the `stopping` code could be called.
