### ISSUE TITLE
Output ports + subscriptions

### ISSUE THREAD

**Issue by slawlor** [slawlor/ractor#4]
We should be able to setup an "output" port kind of publish-subscribe model so actors can "emit" messages without knowing exactly who is listening. 

This would require actors to emit some kind of ports which can be wired up to with a disposable (drop-able) handle to the subscription

**Comment by slawlor** [comment]
#14 adds support for output ports, but their syntax is kind of clunky. It'd be great if a struct could implement a trait which would add support onto `ActorRef` or `ActorCell` to subscribing to a given port (even if it's only 1).

So say if `ActorRef<TActor> where TActor: ActorHandler + ActorOutput` then implement the subscription...

**Comment by FancyQian** [comment]
Not sure, why reopen it?
