### ISSUE TITLE
Add utility actors

### ISSUE THREAD

**Issue by slawlor** [slawlor/ractor#45]
We have a `gen_server` equivalent (basic actor), now we can expand on that

* [x] `factory` for a pool of workers local to a node #46 , #47 

Other possible utility actors that might be helpful to have:

* [ ] Timer (execute on a period ignore comp time, execute on a period handling comp time taking too long, execute with a delay between, etc)
* [ ] FileWatcher? Watch a specified file (or directory) and notify someone on changes (output-port use case?)
* [ ] Basic networking [tcp/udp] servers and clients? This however might require enforcing some kind of encoding (i.e. length pre-pended frames) or something

**Comment by c0d3x42** [comment]
Hi there, I found your crate just recently, great work BTW!, and one of the first things i tried implementing with it was a FileWatcher.
Its currently tailored to my use case, and i did indeed end up using ports. 
Under the hood its using the `notify` crate, how would you feel about that as a dependency?
I'd be happy contribute a cleaned up version of my code if you could give some directions?  I mean, i'm happy with making MR's, but should I put the code in a new dir, seperate crate, that kinda stuff.

**Comment by slawlor** [comment]
Yeah if you're going to add dependencies and things that are somewhat special, I think the best course of action would be a new crate that can be published separately in the workspace. The core `ractor` crate is and should remain small and lightweight without a ton of dependencies. 

The other option however is to add a new module (and sub-modules) and enable it on `ractor` with a feature annotation. Both are good and I'm not really partial to either. Keeping it in the same crate with a feature makes publishing probably somewhat easier.

Thanks!

**Comment by c0d3x42** [comment]
probably not going to have much time to devote to this till next weekend, but it'll give me a bit more time to think about it, which is good coz what i've got is a little rough around the edges at the mo.

**Comment by slawlor** [comment]
Moving to https://github.com/slawlor/ractor_actors (new repo for independent crate of utility actors)
