### ISSUE TITLE
send_interval can drift

### ISSUE THREAD

**Issue by tbillington** [slawlor/ractor#57]
Based on the [implementation](https://github.com/slawlor/ractor/blob/3736464ac00c92bad93f07d47e056dd66fc95030/ractor/src/time/mod.rs#L43) of `send_interval` being through sleeping, the interval will drift over time in long running programs.

The sources of drift can come from both the sleep timer potentially not being woken up on time, and the time taken to run the user code to produce the message, `send_message` itself, and the loop mechanism will all introduce delay before the next call to `sleep`.

Since the sleep period does not take into account the delta between the last and current, it is unable to compensate for added execution time and therefore will be subject to drift over time.

As a source of prior art, the tokio [`Interval`](https://docs.rs/tokio/latest/tokio/time/struct.Interval.html) default behaviour accounts for this and will [schedule the next accordingly](https://github.com/tokio-rs/tokio/blob/c89406965ffb4a64936d781c556a2c48855dfbdb/tokio/src/time/interval.rs#L471-L483). This behaviour can be configured on the interval through `set_missed_tick_behavior` with a [`MissedTickBehaviour`](https://docs.rs/tokio/latest/tokio/time/enum.MissedTickBehavior.html).

**Comment by slawlor** [comment]
Thanks for this! This is indeed a bug, and we can address it with [Interval](https://docs.rs/tokio/latest/tokio/time/fn.interval.html)
