### ISSUE TITLE
Do ractor have persistence feature？

### ISSUE THREAD

**Issue by lshoo** [slawlor/ractor#74]
Can Actor state store to physicial storage，and restore Actor state from storage？e.g. Akka-persistence

**Comment by slawlor** [comment]
Presently no we don't have any support for that, however you could wire up something in on-start and on-stop to deal with data persistence. We could probably build in something automated, but we haven't scoped or included it.

As a note post_start + post_stop are both captured during supervision, pre_start is not so if you did persistence calls I would recommend keeping that in mind to understand when a failure could occur especially with IO operations.

**Comment by lshoo** [comment]
How long will `ractor-cluster` develop completelly?
I want to use persistence and cluster like Akka

**Comment by slawlor** [comment]
It's reasonably stable now, but it requires somewhat manual connection flows at the moment. There's some cleanup there, however it can be built off of. We're using it successfully in other projects now. Are there features you're missing for your use-case?
